version: "3"

services:
    dailygrocery-api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        networks:
            - dailygrocery_network
        environment:
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=dailygrocerydb
            - DB_USERNAME=root
            - DB_PASSWORD=dailygrocerydb$$
        depends_on:
            - dailygrocery-mysql

    dailygrocery-mysql:
        image: mysql:8.0
        container_name: mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: dailygrocerydb$$
            MYSQL_DATABASE: dailygrocerydb
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - dailygrocery_network

    dailygrocery-phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        platform: linux/amd64
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: dailygrocerydb$$
        ports:
            - "8081:81"
        depends_on:
            - dailygrocery-mysql
        networks:
            - dailygrocery_network

volumes:
    mysql_data:

networks:
    dailygrocery_network:
        driver: bridge
